- hosts: localhost
  connection: local
  become: true

  pre-tasks:
    - name: update repostitories
      apt:
        update_cache: yes
        changed_when: False

  tasks:
    - include: tasks/packages.yml